from pynput.keyboard import Key


keys_map = {
    "num0": '0',
    "num1": '1',
    "num2": '2',
    "num3": '3',
    "num4": '4',
    "num5": '5',
    "num6": '6',
    "num7": '7',
    "num8": '8',
    "num9": '9',
    "add": '+',
    "decimal": ',',
    "subtract": '-',
    "multiply": '*',
    "divide": '/',
    "separator": '|',
    "altleft": Key.alt_l,
    "altright": Key.alt_r,
    "capslock": Key.caps_lock,
    "command": Key.cmd,
    "win": Key.cmd,
    "winleft": Key.cmd_l,
    "winright": Key.cmd_r,
    "ctrlleft": Key.ctrl_l,
    "ctrlright": Key.ctrl_r,
    "escape": Key.esc,
    "pagedown": Key.page_down,
    "pageup": Key.page_up,
    "pgdn": Key.page_down,
    "pgup": Key.page_up,
    "shiftleft": Key.shift_l,
    "shiftright": Key.shift_r,
    "playpause": Key.media_play_pause,
    "volumemute": Key.media_volume_mute,
    "volumedown": Key.media_volume_down,
    "volumeup": Key.media_volume_up,
    "prevtrack": Key.media_previous,
    "nexttrack": Key.media_next,
    "numlock": Key.num_lock,
    "printscreen": Key.print_screen,
    "prntscrn": Key.print_screen,
    "prtsc":  Key.print_screen,
    "prtscr": Key.print_screen,
    "print": Key.print_screen,
    "scrolllock": Key.scroll_lock,
    "return": Key.enter
}
